"""modified playlist

Revision ID: 3dcf54d9e4f7
Revises: ed405d6f1936
Create Date: 2024-03-21 18:29:26.473805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcf54d9e4f7'
down_revision: Union[str, None] = 'ed405d6f1936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ptracks', sa.Column('spotify_id', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ptracks', 'spotify_id')
    # ### end Alembic commands ###
