"""removed test property - this is for testing purpose

Revision ID: b1b4fb728f74
Revises: 56cf630a539a
Create Date: 2024-03-09 19:22:05.763627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b4fb728f74'
down_revision: Union[str, None] = '56cf630a539a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
