"""updated firlds for playlist track

Revision ID: ed405d6f1936
Revises: d6e07a564dc3
Create Date: 2024-03-20 12:42:29.730481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed405d6f1936'
down_revision: Union[str, None] = 'd6e07a564dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ptracks', sa.Column('href', sa.String(length=128), nullable=True))
    op.add_column('ptracks', sa.Column('release_date', sa.String(length=128), nullable=True))
    op.add_column('ptracks', sa.Column('image_uri', sa.String(length=128), nullable=True))
    op.add_column('ptracks', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ptracks', 'duration_ms')
    op.drop_column('ptracks', 'image_uri')
    op.drop_column('ptracks', 'release_date')
    op.drop_column('ptracks', 'href')
    # ### end Alembic commands ###
